version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"
