name: Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Patch version
        run: yarn version --patch
      - name: Publish
        run: yarn publish
